class DummyJson {
  static DummyJson instance = DummyJson._init();

  DummyJson._init();

  final String hospitalAll = "{\"section_id\":100,\"section_name\":\"Rumah Sakit\",\"section_type\":\"hospital\",\"filter\":[{\"id\":0,\"name\":\"SEMUA\"},{\"id\":1,\"name\":\"BPJS\"},{\"id\":2,\"name\":\"Partner\"},{\"id\":3,\"name\":\"Terdekat\"},{\"id\":4,\"name\":\"Terfavorit\"}],\"data\":[{\"id\":3173543,\"name\":\"RS Abdi Waluyo\",\"address\":\"Jalan HOS. Cokroaminoto No. 31, Gondangdia, Kec. Menteng, Kota Administrasi Jakarta Pusat, DKI Jakarta 10350\",\"thumbnail\":\"https://play-lh.googleusercontent.com/7YTe_tk2wnRlykLU_LrFRDu73Kb06mpZ6oYogFNh4OFKYSVKNvoPiIASPcpkXmGVfBE\"},{\"id\":3173706,\"name\":\"RS Hermina Kemayoran\",\"address\":\"Jalan Selangit No. 10, Gunung Sahari Selatan Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10620\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/09120825/Rumah-Sakit-Hermina-e1594271322678.jpg\"},{\"id\":3173040,\"name\":\"RS Husada\",\"address\":\"Jalan Mangga Besar No. 137, Mangga Dua Selatan, Kec. Sawah Besar, Kota Administrasi Jakarta Pusat, DKI Jakarta 10730\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/16181851/Rumah-Sakit-Husada-e1594898356181.jpg\"},{\"id\":3173073,\"name\":\"RS Islam Jakarta\",\"address\":\"Jalan Cempaka Putih Tengah I No. 1, Cempaka Putih Timur, Kec. Cempaka Putih, Kota Administrasi Jakarta Pusat, DKI Jakarta 10510\",\"thumbnail\":\"https://1.bp.blogspot.com/-IOvPFv8pva8/V2vloXUU9ZI/AAAAAAAADU8/ahQGMaUut0wRi4bJzXaT6yLPJDsv4N6FwCLcB/s1600/RUMAH%2BSAKIT%2BISLAM%2BJAKARTA.png\"},{\"id\":3173656,\"name\":\"RS Mitra Keluarga Kemayoran\",\"address\":\"Jalan HBR. Motik No. 12, Kebon Kosong, Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10630\",\"thumbnail\":\"https://www.mitrakeluarga.com/mitra-keluarga-image.jpg\"}]}";
  final String hospitalBpjs = "{\"section_id\":100,\"section_name\":\"Rumah Sakit\",\"section_type\":\"hospital\",\"filter\":[{\"id\":0,\"name\":\"SEMUA\"},{\"id\":1,\"name\":\"BPJS\"},{\"id\":2,\"name\":\"Partner\"},{\"id\":3,\"name\":\"Terdekat\"},{\"id\":4,\"name\":\"Terfavorit\"}],\"data\":[{\"id\":3173706,\"name\":\"RS Hermina Kemayoran\",\"address\":\"Jalan Selangit No. 10, Gunung Sahari Selatan Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10620\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/09120825/Rumah-Sakit-Hermina-e1594271322678.jpg\"},{\"id\":3173040,\"name\":\"RS Husada\",\"address\":\"Jalan Mangga Besar No. 137, Mangga Dua Selatan, Kec. Sawah Besar, Kota Administrasi Jakarta Pusat, DKI Jakarta 10730\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/16181851/Rumah-Sakit-Husada-e1594898356181.jpg\"},{\"id\":3173656,\"name\":\"RS Mitra Keluarga Kemayoran\",\"address\":\"Jalan HBR. Motik No. 12, Kebon Kosong, Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10630\",\"thumbnail\":\"https://www.mitrakeluarga.com/mitra-keluarga-image.jpg\"}]}";
  final String hospitalPartner = "{\"section_id\":100,\"section_name\":\"Rumah Sakit\",\"section_type\":\"hospital\",\"filter\":[{\"id\":0,\"name\":\"SEMUA\"},{\"id\":1,\"name\":\"BPJS\"},{\"id\":2,\"name\":\"Partner\"},{\"id\":3,\"name\":\"Terdekat\"},{\"id\":4,\"name\":\"Terfavorit\"}],\"data\":[{\"id\":3173543,\"name\":\"RS Abdi Waluyo\",\"address\":\"Jalan HOS. Cokroaminoto No. 31, Gondangdia, Kec. Menteng, Kota Administrasi Jakarta Pusat, DKI Jakarta 10350\",\"thumbnail\":\"https://play-lh.googleusercontent.com/7YTe_tk2wnRlykLU_LrFRDu73Kb06mpZ6oYogFNh4OFKYSVKNvoPiIASPcpkXmGVfBE\"},{\"id\":3173073,\"name\":\"RS Islam Jakarta\",\"address\":\"Jalan Cempaka Putih Tengah I No. 1, Cempaka Putih Timur, Kec. Cempaka Putih, Kota Administrasi Jakarta Pusat, DKI Jakarta 10510\",\"thumbnail\":\"https://1.bp.blogspot.com/-IOvPFv8pva8/V2vloXUU9ZI/AAAAAAAADU8/ahQGMaUut0wRi4bJzXaT6yLPJDsv4N6FwCLcB/s1600/RUMAH%2BSAKIT%2BISLAM%2BJAKARTA.png\"}]}";
  final String hospitalTerdekat = "{\"section_id\":100,\"section_name\":\"Rumah Sakit\",\"section_type\":\"hospital\",\"filter\":[{\"id\":0,\"name\":\"SEMUA\"},{\"id\":1,\"name\":\"BPJS\"},{\"id\":2,\"name\":\"Partner\"},{\"id\":3,\"name\":\"Terdekat\"},{\"id\":4,\"name\":\"Terfavorit\"}],\"data\":[{\"id\":3173543,\"name\":\"RS Abdi Waluyo\",\"address\":\"Jalan HOS. Cokroaminoto No. 31, Gondangdia, Kec. Menteng, Kota Administrasi Jakarta Pusat, DKI Jakarta 10350\",\"thumbnail\":\"https://play-lh.googleusercontent.com/7YTe_tk2wnRlykLU_LrFRDu73Kb06mpZ6oYogFNh4OFKYSVKNvoPiIASPcpkXmGVfBE\"},{\"id\":3173040,\"name\":\"RS Husada\",\"address\":\"Jalan Mangga Besar No. 137, Mangga Dua Selatan, Kec. Sawah Besar, Kota Administrasi Jakarta Pusat, DKI Jakarta 10730\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/16181851/Rumah-Sakit-Husada-e1594898356181.jpg\"}]}";
  final String hospitalTerfavorit = "{\"section_id\":100,\"section_name\":\"Rumah Sakit\",\"section_type\":\"hospital\",\"filter\":[{\"id\":0,\"name\":\"SEMUA\"},{\"id\":1,\"name\":\"BPJS\"},{\"id\":2,\"name\":\"Partner\"},{\"id\":3,\"name\":\"Terdekat\"},{\"id\":4,\"name\":\"Terfavorit\"}],\"data\":[{\"id\":3173543,\"name\":\"RS Abdi Waluyo\",\"address\":\"Jalan HOS. Cokroaminoto No. 31, Gondangdia, Kec. Menteng, Kota Administrasi Jakarta Pusat, DKI Jakarta 10350\",\"thumbnail\":\"https://play-lh.googleusercontent.com/7YTe_tk2wnRlykLU_LrFRDu73Kb06mpZ6oYogFNh4OFKYSVKNvoPiIASPcpkXmGVfBE\"},{\"id\":3173706,\"name\":\"RS Hermina Kemayoran\",\"address\":\"Jalan Selangit No. 10, Gunung Sahari Selatan Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10620\",\"thumbnail\":\"https://blog-media.lifepal.co.id/app/uploads/sites/3/2020/07/09120825/Rumah-Sakit-Hermina-e1594271322678.jpg\"},{\"id\":3173656,\"name\":\"RS Mitra Keluarga Kemayoran\",\"address\":\"Jalan HBR. Motik No. 12, Kebon Kosong, Kec. Kemayoran, Kota Administrasi Jakarta Pusat, DKI Jakarta 10630\",\"thumbnail\":\"https://www.mitrakeluarga.com/mitra-keluarga-image.jpg\"}]}";

  final String bannerAll = "{\"data\":[{\"id\":100,\"name\":\"Promo 17 Agustus\",\"thumbnail\":\"https://i.ytimg.com/vi/VLBYbrYanPU/maxresdefault.jpg\"},{\"id\":101,\"name\":\"Promo 17 Agustus\",\"thumbnail\":\"https://i.ytimg.com/vi/VLBYbrYanPU/maxresdefault.jpg\"},{\"id\":102,\"name\":\"Promo 17 Agustus\",\"thumbnail\":\"https://i.ytimg.com/vi/VLBYbrYanPU/maxresdefault.jpg\"}]}";
}